### ISSUE TITLE
在已安 Xcode 的情况下运行 xcode-select -p

### ISSUE THREAD

**Issue by changsj** [pubyun/macdev#12]
在刚从 MAS 安装完 Xcode 的情况下，我运行 $ xcode-select -p
我的结果是 /Applications/Xcode.app/Contents/Developer
而不是文中说的 /Library/Developer/CommandLineTools

然后我进入 “资源库” 发现有 /Library/Developer/CommandLineTools 这个目录，大小为 230 M

**Comment by pubyun** [comment]
fix in #1f350b
